// <auto-generated />
using System;
using Hauler_Up.Infastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hauler_Up.Infastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220930160516_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hauler_Up.Domain.Models.Catch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Canner")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Market")
                        .HasColumnType("int");

                    b.Property<int>("TrawlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrawlId");

                    b.ToTable("Catch", (string)null);
                });

            modelBuilder.Entity("Hauler_Up.Domain.Models.Trawl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Trawl", (string)null);
                });

            modelBuilder.Entity("Hauler_Up.Domain.Models.Catch", b =>
                {
                    b.HasOne("Hauler_Up.Domain.Models.Trawl", "Trawl")
                        .WithMany("Catches")
                        .HasForeignKey("TrawlId")
                        .IsRequired();

                    b.Navigation("Trawl");
                });

            modelBuilder.Entity("Hauler_Up.Domain.Models.Trawl", b =>
                {
                    b.Navigation("Catches");
                });
#pragma warning restore 612, 618
        }
    }
}
